---
name: Push to GitHub Packages

on:
  push:
    branches:
      - "master"
    tags:
      - "*"
  workflow_dispatch:

jobs:
  latest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository: YoRyan/mailrise
      - name: Checkout
        uses: actions/checkout@v5
        with:
          path: builder
      - name: Apply patch
        run: git apply builder/apprise.patch
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: ./builder/.github/actions/docker-build
        with:
          images: ghcr.io/gwelican/mailrise
