---
name: Push to GitHub Packages
# renovate: datasource=github-releases depName=YoRyan/mailrise
# version: 1.4.0

on:
  push:
    branches:
      - "master"
    tags:
      - "*"
  workflow_dispatch:

jobs:
  latest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: YoRyan/mailrise
          path: mailrise
      - name: Apply patch
        run: find .
      - name: Apply patch
        working-directory: mailrise
        run: git apply ../apprise.patch
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          path: mailrise
      - name: Build and Push
        uses: ./.github/actions/docker-build
        with:
          images: ghcr.io/gwelican/mailrise
